page_title: Sitemap
message:
  value: ''
  format: full_html
show_front: true
show_titles: true
show_books: {  }
books_expanded: true
show_menus:
  footer: footer
  main: main
  social-menu: social-menu
  account: '0'
  admin: '0'
  tools: '0'
show_menus_hidden: false
show_vocabularies:
  tags: '0'
show_description: true
show_count: true
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 1
rss_taxonomy: -1
css: true
order:
  front: -50
  menus_account: -49
  menus_admin: -48
  menus_main: -47
  menus_social-menu: -46
  menus_footer: -45
  menus_tools: -44
  vocabularies_tags: -43
_core:
  default_config_hash: yUNkiSB-fp4pyUb6B2L9HiiCdISBDvK7r1v9_XkGUaQ
